### get all games
get http://localhost:3000/games

### get game by id
get http://localhost:3000/games/3

### delete game by id
DELETE http://localhost:3000/games/12


### not available game id 
DELETE http://localhost:3000/games/11

### post game

post http://localhost:3000/games
Content-Length: application/json
{
    "GNames": "Forma 1  Serie",
    "TId": 3,
    "MoS": "Multi and single"
}


### put a game
PUT http://localhost:3000/games/12
Content-Length: application/json

{
    "GNames": "Roblox",
    "TId": ,
    "MoS": "Multi"
}

### get all type
get http://localhost:3000/types

### get type by id
get http://localhost:3000/types/3

### delete type by id
DELETE http://localhost:3000/types/7



### not available type id 
DELETE http://localhost:3000/types/11

### post type

post http://localhost:3000/types
Content-Length: application/json
{
    "TName": "Puzzle"
}


### put a game
PUT http://localhost:3000/types/7
Content-Length: application/json

{
    "TName": "Retro"
}