### get all games
get http://localhost:3000/games

### get game by id
get http://localhost:3000/games/3

### delete game by id
DELETE http://localhost:3000/games/6



### post game

post http://localhost:3000/games
Content-Type: application/json

{
    "GNames": "Forma 1  Serie",
    "TId": 3,
    "MorS": "Multi and single"
}


### put a game
put http://localhost:3000/games/1
Content-Type: application/json

{
    "GNames": "Two Point Hospital",
    "TId": 6,
    "MorS": "Singleplayer"
}

### get all type
get http://localhost:3000/types

### get type by id
get http://localhost:3000/types/3

### delete type by id
DELETE http://localhost:3000/types/7



### not available type id 
DELETE http://localhost:3000/types/11

### post type

post http://localhost:3000/types
Content-Type: application/json
{
    "TName": "Puzzle"
}


### put a game
PUT http://localhost:3000/types/7
Content-Type: application/json

{
    "TName": "Retro"
}